add_newline = false

[nodejs]
detect_folders = []
format = '\[[$symbol($version)]($style)\]'

[shell]
disabled = true

[memory_usage]
disabled = true

# Make prompt a single line instead of two lines
[line_break]
disabled = false

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

